### ISSUE TITLE
cannot find sqlFluff Executable -- Windows + virtual environment issue?

### ISSUE THREAD

**Issue by cnolanminich** [dorzey/vscode-sqlfluff#4]
I'm having trouble getting the extension to "find" my version of sqlfluff. I'm using Windows 10, pipenv for virtual environment management, and below is some info that _might_ shed light on the issue?

`pipenv --py`
> C:\Users\[USER]\.virtualenvs\[PROJNAME]-cP1ijf-7\Scripts\python.exe
```bash
pipenv shell
sqlfluff --version
```
> sqlfluff, version 0.3.5
settings.json in VS Code contains:
```json 
"sql.linter.executablePath":
"C:\\Users\\[USER]\\.virtualenvs\\[PROJECT]-cP1ijf-7\\Scripts\\sqlfluff.exe",
```

When I open a SQL file in VS Code, I get the following error message:

> The executable was not found, Use the 'sql,jinja-sql.executablePath' setting to configure the location of the executable.

When I copy the `sqlfluff.exe` file directly into the main project I'm in, the extension works like a charm.

**Comment by cnolanminich** [comment]
OK, I got to the bottom of this. My idea was not to add the virtual environment to the PATH, but that was necessary in order for this to work. 

I'm a bit confused as to what the `sql.linter.executablePath`, if the executable also needs to be on the PATH, but I don't currently have an issue. Thanks for creating this extension 🚀

**Comment by reubster** [comment]
Hi @cnolanminich , 

I'm experiencing this at the moment, and I'm not sure exactly what your fix was. When you say "PATH" do you mean the host os PATH setting? or the virtual env?

**Comment by skaylie** [comment]
this is very frustrating as i still get the same error:  "The sqlfluff executable was not found. Use the 'Executable Path' setting to configure the location of the executable, or add it to your PATH."

Is there anyone working on a windows machine that's gotten the vscode plugin to work?  **Can someone please post a CONCRETE EXAMPLE of what the inputs are supposed to look like to input the path to the executable.**

**Comment by ncalm** [comment]
@skaylie I'm brand new to SQLFluff. 

The first thing I tried was to install the SQLFluff extension in VS Code. I wasn't using a virtual environment at the time. 

This produced the same error - "The sqlfluff executable was not found...etc". 

What isn't clear about the extension is that: 
**_You must install python and then install sqlfluff via pip if you want to use the extension._** 

So, I created a conda environment. Installed python using the Anaconda interface. Then opened an anaconda command prompt in that environment and used pip install sqlfluff:
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/23016780/379586da-e72d-4070-a81c-6921c6ceee17)

This completed without error. After which, open VS Code from within the environment:
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/23016780/588b0fda-381d-46eb-813f-86001d35094d)

After doing this, I no longer have the error and I can use the linter by running sqlfluff lint --dialect mydialect in the VS Code terminal. 
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/23016780/e4805c82-0894-4278-aca6-3c1fe7d4692d)

Linting doesn't appear to happen as I type, so I will play with some settings to see what can be done.

**Comment by RobertOstermann** [comment]
@ncalm Here are some settings that might be useful to you.

```json
"sqlfluff.dialect": "tsql",
"sqlfluff.linter.delay": 500,
// onType should be default value so not sure why it would not be linting onType for you.
"sqlfluff.linter.run": "onType",
```

I should update the README to make it clear that sqlfluff must be installed separately.

If linting is not working for you still, you could check the OUTPUT tab (next to terminal) and see the SQLFluff channel, it will tell you which commands are being run.

**Comment by reubster** [comment]
@ncalm 
My thoughts; 

1/ Do you have the vscode settings for sqlfluff in place? I think it needs to know where the .exe is in your virtual environment. I think it's normally; 
<absolute path>/.venv/.sqlfluff

Mine also has;

<img width="662" alt="image" src="https://github.com/sqlfluff/vscode-sqlfluff/assets/19515061/ff87f931-707f-4961-bd1d-78c23a41dcc1">

2/ If you're using dbt, the other thing I need to do to get it to work was to ensure my profiles.yml was not using any environment variables. Basically dbt needs to work before sqlfluff can work, if you're linting dbt code. 

3/ the SQFluff extension will produce logging in Vscode Output tab - SQLFLuff log, or failing that in the Extension Host log.

**Comment by RobertOstermann** [comment]
@ncalm This should give an example of setting the upper case keywords [rule-configuration](https://docs.sqlfluff.com/en/stable/configuration.html#rule-configuration). The configuration file might be recognized automatically, but if not you can use the `"sqlfluff.config"` setting to set the path of the configuration file.

**Comment by patrick-wood-vph** [comment]
I still seem to be having an issue getting vscode to 'see' the executable. exe seems to be in a standardized location.  I have attempted using:
this: C:/Users/pwood/AppData/Roaming/Python/Python311/Scripts/sqlfluff.exe
this: C:\\Users\\pwood\\AppData\\Roaming\\Python\\Python311\\Scripts\\sqlfluff.exe
this: sqlfluff
and this: sqlfluff.exe
I had assumed one of those paths would have pointed to the exe that is at that path.  
Does anyone else know of anything else I might need to do to get this to work?

**Comment by RobertOstermann** [comment]
Try running the `SQLFluff Debug Extension` command and let me know what the results are. That command should tell you where the failure is happening.

If it is indeed at the sqlfluff executable, it should attempt to find the path that you could use.

**Comment by patrick-wood-vph** [comment]
It looks like this might be a workspace issue like referenced in another issue id.
I am working from azure repos remote.  When I open a local folder, it works just fine.
Do you know off the top of your head, if it ‘should’ work w/ azure repos?

**Comment by RobertOstermann** [comment]
I am not sure if it should/would work in a remote repo. I have only set it up and tried it with a local repository or through WSL.

You could manually set the working directory and see if that works.
