### ISSUE TITLE
Joining sqlfluff org

### ISSUE THREAD

**Issue by pwildenhain** [dorzey/vscode-sqlfluff#5]
👋 Hello there!

First off, great plugin 💯 🔌 💖 I use it daily 🙇‍♂️ 

@alanmcruickshank recently transferred the `sqlfluff` project to it's own [github org](https://github.com/sqlfluff), and has started adding members who are interested in the project's continued success. We're also trying to gauge interest in moving related repos under the same org, as @nolanbconaway did with his [online `sqlfluff` formatter](https://sqlfluff-online.herokuapp.com/)

Two questions for you:
1. Would you be interested in joining the `sqlfluff` org?
2. Would you be interested in moving this repo under the `sqlfluff` org? (while retaining the same rights 🔐 )

**Comment by dorzey** [comment]
Yes and yes

**Comment by pwildenhain** [comment]
Great! I'll let you and @alanmcruickshank take it from here, welcome to the club 🍻

**Comment by alanmcruickshank** [comment]
Heya @dorzey. Process from here:

1. You should already have an invite to the github org. You'll need to click the associated links which should you set you up as one of the maintainers of sqlfluff and let you edit stuff within the org.
2. The instructions for shifting a repo over to the org are here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account
3. Once you initiate the transfer I think I'll need to click a link in an email somewhere to ok it on the way in, so there might be a delay while I do that.
4. After that the repo will live within the org. Any links to the current repo should still work and redirect, but it's probably worth transferring any links over and any CI pipelines etc...
5. By default, you'll have *most* permissions as part of the _maintainers_ team, but I'll escalate you to a full admin specifically on the `vscode-sqlfluff` repo. I can't do that until the repository is transferred though so there might be a delay in you being able to do anything destructive until that point 😄 . I've made a note here to do that when the transfer is complete, but if for whatever reason it looks like I haven't done it or you're have trouble doing anything then feel free to either message me or raise an issue in one of the repos to @ me. You'll see a very similar process in this issues where we shook out all the issues for [sqlfluff and  sqlfluff-online](https://github.com/sqlfluff/sqlfluff/issues/444)

**Comment by dorzey** [comment]
I've accepted the invite to the org.

I might not get chance to move the repo to the weekend. Thanks for the instructions!

**Comment by dorzey** [comment]
@alanmcruickshank I've transferred the ownership. I was using GitHub Actions for CI so they've moved across.

https://marketplace.visualstudio.com/items?itemName=dorzey.vscode-sqlfluff - Is still published under `dorzey`; do we want to create a `sqlfluff` publisher?

**Comment by pwildenhain** [comment]
I think thats a 💯 idea!

**Comment by alanmcruickshank** [comment]
@dorzey - I've just upgraded you to an admin on the repo so you should have all the access you used to back.

As for the sqlfluff publisher - that sounds like a great idea. Go ahead!
